# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import warehouse_pb2 as warehouse__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in warehouse_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WarehouseServiceStub(object):
    """Servicio principal que expone las operaciones
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCoords = channel.unary_unary(
                '/warehouse.WarehouseService/GetCoords',
                request_serializer=warehouse__pb2.Empty.SerializeToString,
                response_deserializer=warehouse__pb2.CoordsResponse.FromString,
                _registered_method=True)
        self.Pickup = channel.unary_unary(
                '/warehouse.WarehouseService/Pickup',
                request_serializer=warehouse__pb2.PickupRequest.SerializeToString,
                response_deserializer=warehouse__pb2.Ack.FromString,
                _registered_method=True)
        self.Drop = channel.unary_unary(
                '/warehouse.WarehouseService/Drop',
                request_serializer=warehouse__pb2.DropRequest.SerializeToString,
                response_deserializer=warehouse__pb2.Ack.FromString,
                _registered_method=True)
        self.AssignTask = channel.unary_unary(
                '/warehouse.WarehouseService/AssignTask',
                request_serializer=warehouse__pb2.AssignRequest.SerializeToString,
                response_deserializer=warehouse__pb2.Ack.FromString,
                _registered_method=True)


class WarehouseServiceServicer(object):
    """Servicio principal que expone las operaciones
    """

    def GetCoords(self, request, context):
        """Sustituye GET /coords
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pickup(self, request, context):
        """Sustituye POST /pickup
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Drop(self, request, context):
        """Sustituye POST /drop
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignTask(self, request, context):
        """Sustituye POST /assign
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WarehouseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCoords': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCoords,
                    request_deserializer=warehouse__pb2.Empty.FromString,
                    response_serializer=warehouse__pb2.CoordsResponse.SerializeToString,
            ),
            'Pickup': grpc.unary_unary_rpc_method_handler(
                    servicer.Pickup,
                    request_deserializer=warehouse__pb2.PickupRequest.FromString,
                    response_serializer=warehouse__pb2.Ack.SerializeToString,
            ),
            'Drop': grpc.unary_unary_rpc_method_handler(
                    servicer.Drop,
                    request_deserializer=warehouse__pb2.DropRequest.FromString,
                    response_serializer=warehouse__pb2.Ack.SerializeToString,
            ),
            'AssignTask': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignTask,
                    request_deserializer=warehouse__pb2.AssignRequest.FromString,
                    response_serializer=warehouse__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'warehouse.WarehouseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('warehouse.WarehouseService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WarehouseService(object):
    """Servicio principal que expone las operaciones
    """

    @staticmethod
    def GetCoords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/warehouse.WarehouseService/GetCoords',
            warehouse__pb2.Empty.SerializeToString,
            warehouse__pb2.CoordsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Pickup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/warehouse.WarehouseService/Pickup',
            warehouse__pb2.PickupRequest.SerializeToString,
            warehouse__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Drop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/warehouse.WarehouseService/Drop',
            warehouse__pb2.DropRequest.SerializeToString,
            warehouse__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssignTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/warehouse.WarehouseService/AssignTask',
            warehouse__pb2.AssignRequest.SerializeToString,
            warehouse__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
