# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: warehouse.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'warehouse.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fwarehouse.proto\x12\twarehouse\"\x07\n\x05\x45mpty\"+\n\x08Position\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"N\n\nObjectData\x12\n\n\x02id\x18\x01 \x01(\t\x12%\n\x08position\x18\x02 \x01(\x0b\x32\x13.warehouse.Position\x12\r\n\x05speed\x18\x03 \x01(\x01\"K\n\x0e\x43oordsResponse\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12&\n\x07objects\x18\x02 \x03(\x0b\x32\x15.warehouse.ObjectData\"+\n\rPickupRequest\x12\r\n\x05\x61gent\x18\x01 \x01(\t\x12\x0b\n\x03\x62ox\x18\x02 \x01(\t\"P\n\x0b\x44ropRequest\x12\r\n\x05\x61gent\x18\x01 \x01(\t\x12\x0b\n\x03\x62ox\x18\x02 \x01(\t\x12%\n\x08position\x18\x03 \x01(\x0b\x32\x13.warehouse.Position\"P\n\rAssignRequest\x12\r\n\x05\x61gent\x18\x01 \x01(\t\x12\x0b\n\x03\x62ox\x18\x02 \x01(\t\x12#\n\x06target\x18\x03 \x01(\x0b\x32\x13.warehouse.Position\" \n\x03\x41\x63k\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\xe8\x01\n\x10WarehouseService\x12\x38\n\tGetCoords\x12\x10.warehouse.Empty\x1a\x19.warehouse.CoordsResponse\x12\x32\n\x06Pickup\x12\x18.warehouse.PickupRequest\x1a\x0e.warehouse.Ack\x12.\n\x04\x44rop\x12\x16.warehouse.DropRequest\x1a\x0e.warehouse.Ack\x12\x36\n\nAssignTask\x12\x18.warehouse.AssignRequest\x1a\x0e.warehouse.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'warehouse_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=30
  _globals['_EMPTY']._serialized_end=37
  _globals['_POSITION']._serialized_start=39
  _globals['_POSITION']._serialized_end=82
  _globals['_OBJECTDATA']._serialized_start=84
  _globals['_OBJECTDATA']._serialized_end=162
  _globals['_COORDSRESPONSE']._serialized_start=164
  _globals['_COORDSRESPONSE']._serialized_end=239
  _globals['_PICKUPREQUEST']._serialized_start=241
  _globals['_PICKUPREQUEST']._serialized_end=284
  _globals['_DROPREQUEST']._serialized_start=286
  _globals['_DROPREQUEST']._serialized_end=366
  _globals['_ASSIGNREQUEST']._serialized_start=368
  _globals['_ASSIGNREQUEST']._serialized_end=448
  _globals['_ACK']._serialized_start=450
  _globals['_ACK']._serialized_end=482
  _globals['_WAREHOUSESERVICE']._serialized_start=485
  _globals['_WAREHOUSESERVICE']._serialized_end=717
# @@protoc_insertion_point(module_scope)
